### ISSUE TITLE
metric methods

### ISSUE THREAD

**Issue by oomq** [TencentARC/UMT#21]
Hello, I am very interested in your research.
In the evaluation method, after you sort the predicted scores, you do not use them any more, but only use the real [labels](https://github.com/TencentARC/UMT/blob/main/datasets/youtube.py#:~:text=in%20enumerate(-,label,-)%3A) corresponding to the sorted scores for prediction.  Why?
And there is no detailed explanation of the mAP metric method in the paper. Is there any reference?

**Comment by yeliudev** [comment]
Thanks for your interest in our work!

The `labels` is a list of ones and zeros indicating whether each clip is a highlight or not. We use [argsort](https://github.com/TencentARC/UMT/blob/main/datasets/youtube.py#L26) to obtain the sorted indexes of predicted highlight clips, so that the sum of `labels[inds][:1]` or `labels[inds][:5]` denotes the Recall@1 and Recall@5 values respectively. The mAP values can also be computed using this sorted label list.

As for the metrics, we follow the definition of mAP mentioned in [this](https://arxiv.org/abs/1903.00859) paper.

**Comment by oomq** [comment]
Thanks for your reply.

The sorted label list seems to be real labels. Shouldn't we use the predicted label to calculate mAP values?

**Comment by yeliudev** [comment]
Yes, the sorted labels are ground truths, but they are sorted according to the predicted scores. For example, if the first 5 elements in the sorted label list are `[1, 1, 1, 0, 1]`, we can say that the Recall@5 for this video should be `(1 + 1 + 1 + 0 + 1) / 5 = 0.8`. We use this trick to calculate mAP more efficiently.

**Comment by oomq** [comment]
Thank you, I get it.

1. But I still have a question, can this retrieval metrics be used for classification?

2. If I calculate the predicted label based on the predicted score by setting a threshold, and then calculate the Recall, Precision and AP. Which one is better for classification, this or question 1? 
   Is this metrics design reasonable?

3. When testing another real video,  I don't know its real match. But I need to annotate it if I want to run the code. What can I do to get the correct mAP?

**Comment by yeliudev** [comment]
1. Video highlight detection can indeed be regarded as a clip-level binary classification problem. But I'm not sure about what do you mean by 'use this retrieval metric for classification'.
2. Generally recalls are more suitable for retrieval problems, while precisions are for classification problems.
3. If you want to obtain the mAP for this video, the ground truth annotations are needed.

**Comment by oomq** [comment]
Thank you so much for your help!
