### ISSUE TITLE
Attention map visualization

### ISSUE THREAD

**Issue by G-Apple1** [TencentARC/UMT#36]
How to plot the attention map like paper MBT Figure 6?
I see that the feature sequence after the pre -training model is extracted. How to map attention to the original video？  
Hope you can give me some advice.

![image](https://user-images.githubusercontent.com/62458945/223713846-2e6185fa-faee-42dd-8258-5efc66bb7b5c.png)

**Comment by yeliudev** [comment]
You may try to adopt CAM or Grad-CAM on the feature extractors to visualize the attention maps.

**Comment by Lynne-yyq** [comment]
> You may try to adopt CAM or Grad-CAM on the feature extractors to visualize the attention maps.

Hello author, I would also like to ask about how to implement a heatmap for sounds. 
1) Since the fusion framework is not an end-to-end task and the input to the attention framework is a sequence of features, how can we implement this attention heatmap on the feature extractors? 
2) Additionally, since the input to the attention fusion framework is a sequence of features and the attention heatmap is directly visualized, how do we map it onto an image? Is this approach reasonable?
