### ISSUE TITLE
Any idea of model's general highlight effectiveness

### ISSUE THREAD

**Issue by JW-xiilab** [TencentARC/UMT#41]
Hi, thanks a lot for decent work. 

I want to ask you about the models' general highlight performance. 

In the paper, such as evaluation on QVHighlights dataset and Charades, the model quite seems to have fine performance in detecting highlights of the videos without the text-quires. However, you have only done domain specific (i.e. 7 domains and 10 domains for Youtube Highlights and TVSum datasets, respectively) evaluation on your model.

Is there any reason why you have trained the model on each domain? Because it seems the model is cable of detecting highlights on multi-domain structure. 

I would like to generate the general model to detect highlight from the video. 
Do you think that training on YouTube highlights and TVSum in a multi-domain setting would just result in an awful model? Even considering the performance degradation due to the multi-domain setting?

**Comment by yeliudev** [comment]
Thanks for your interest in our paper. Yes, this is a good question. In the paper, we train a model for each domain to make our method comparable with previous methods, as this is a common setting in previous works. We totally agree that this setting is quite wired since highlights shall not be restricted by the videos' domains. We've tried training the model in a multi-domain setting, but the per-category performance is not as good as single-domain settings. Partially this is because the characteristics of highlights are different in different domains.

**Comment by JW-xiilab** [comment]
Thanks a lot for the reply.

We'll keep that in mind. Appreicate it.
